### ISSUE TITLE
Upgrade registry-image resource to 0.10.0

### ISSUE THREAD

**Issue by jordanbcooper** [concourse/concourse-bosh-release#109]
#Feature Request

## What challenge are you facing?

registry-image resource appears to be out of date and does not support new sts authentication method (aws_session_token)

```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31mERRO[0m[0000] invalid payload: json: unknown field "aws_session_token" 
```

## A Modest Proposal

Should be able to use the aws_session_token to `put` docker images to AWS ECR, but the release appears out of date for this bosh release.

https://github.com/concourse/registry-image-resource/pull/161

**Comment by jordanbcooper** [comment]
Turns out the output for fly workers -d --json

```
     {
        "type": "registry-image",
        "image": "/var/vcap/data/packages/concourse/2be5af030b08ff34d0523ae3f96fe6a95cc32f1d/resource-types/registry-image/rootfs.tgz",
        "version": "0.9.0",
        "privileged": false,
        "unique_version_history": false
      },
```
Thanks to @vito for pushing 0.10.0 :)

**Comment by vito** [comment]
The upgrade will happen automatically and be shipped in the next Concourse version, so I'll just close this in advance :)

We're aiming for 6.3 in a week or two. 👍
