### ISSUE TITLE
No published 4.2.3

### ISSUE THREAD

**Issue by BooleanCat** [concourse/concourse-bosh-release#13]
# Bug Report

Concourse 4.2.3 has shipped yet I can't seem to find a bosh release. The URL to 4.2.3's bosh release [here](https://concourse-ci.org/download.html) leads to a 404 on bosh.io

**Comment by vito** [comment]
Yep, working on getting this out today.

**Comment by amuessig** [comment]
Still awaiting that security fix..

**Comment by BooleanCat** [comment]
@amuessig If you're deploying the concourse bosh release, we (the garden team) just bumped garden to 1.18.2 on our own concourse alonside concourse 4.2.2 and it works just fine.

**Comment by gaigaslab-operations** [comment]
ETA on this BOSH release?  Just asking...

**Comment by vito** [comment]
@gaigaslab-operations It's available now, sorry for the delay:

https://bosh.io/releases/github.com/concourse/concourse-bosh-release?version=4.2.3
