### ISSUE TITLE
Prepare repo for patch releases

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse-bosh-release#14]
These set of tasks apply only to the 4.2.x branch. If required, we will address 3.13.x branch separately.
Tasks
- [x]  Create release branch(es) on concourse-bosh-release
- [x]  Remove temporary bucket for 3.13.99 
- [x]  Ensure, the src dir in concourse-bosh-release matches the corresponding src dir in concourse/concourse repo
- [x]  Ensure, the pipeline yml in concourse-bosh-release matches the corresponding pipeline yml in concourse/concourse repo
- [x] Update hotfix.yml pipeline config to only use concourse-bosh-release instead of concourse/concourse

Remaining work
- [x] Validate `shipit` and subsequent publish jobs generate the desired artifacts at the appropriate locations
   - finalize release metadata committed to concourse-bosh-release with the commit tagged
   - concourse release tarball in `concourse-releases` bucket
   - commit to 4.2.x branch of concourse-bosh-deployment with new versions of [deps](https://github.com/concourse/concourse-bosh-deployment/blob/release/4.2.x/versions.yml) with the commit tagged

Clean up work - we had temporarily forked repos bumped versions to exercise the pipeline
- [x] Reset version to 4.2.4 ( last released version was 4.2.3 )
- [x] Switch concourse-bosh-release & concourse-bosh-deployment refs to `concourse` org from `chenbh`

**Comment by xtreme-sameer-vohra** [comment]
Remaining work
- [ ] Validate `shipit` and subsequent publish jobs generate the desired artifacts at the appropriate locations
   - finalize release metadata committed to concourse-bosh-release with the commit tagged
   - concourse release tarball in `concourse-releases` bucket
   - commit to 4.2.x branch of concourse-bosh-deployment with new versions of [deps](https://github.com/concourse/concourse-bosh-deployment/blob/release/4.2.x/versions.yml) with the commit tagged

Clean up work - we had temporarily forked repos bumped versions to exercise the pipeline
- [ ] Reset version to 4.2.4 ( last released version was 4.2.3 )
- [ ] Switch concourse-bosh-release & concourse-bosh-deployment refs to `concourse` org from `chenbh`

**Comment by cirocosta** [comment]
>  cirocosta deleted a comment from xtreme-sameer-vohra 

I moved the comment regarding "remaining work" to the initial message such that we can keep track of how much is left from the projects dashboard 👍

**Comment by xtreme-sameer-vohra** [comment]
@cirocosta can we close this off ?
