### ISSUE TITLE
ability to set garden address

### ISSUE THREAD

**Issue by ramonskie** [concourse/concourse-bosh-release#17]
it seems that in v5.0
the ability to set the garden address is removed.
is it a possibility to add this again?

for [BUCC](https://github.com/starkandwayne/bucc) we have multiple jobs that uses garden on one bosh vm with conourse and credhub etc.
so we share one garden-runc.

**Comment by vito** [comment]
What other components use Garden? What do you mean by setting garden address...?

**Comment by ramonskie** [comment]
bosh lite uses garden.
see https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh-lite.yml

**Comment by vito** [comment]
Gotcha. Well, from our side we never really intended to share Garden-runC with any other component, and I'm kind of surprised that worked without issue. I don't think we'll be adding this ourselves, but I'd be happy to review a PR assuming it's easy enough to maintain. I suppose you'd need a flag to prevent the `worker` binary from running its own `gdn`, and to just use a pre-configured Garden address.

Maybe something like `concourse worker --external-garden ip:port`? That flag could be added here:

https://github.com/concourse/concourse/blob/9f34dafd8d94ae2ee947aa52fb8de4f0a8fbe49e/cmd/concourse/worker_linux.go#L28-L35

...and in that case it could return a nil `runner`, though the calling code would have to check for that and know now to try and run it:

https://github.com/concourse/concourse/blob/9f34dafd8d94ae2ee947aa52fb8de4f0a8fbe49e/cmd/concourse/worker.go#L94-L97

**Comment by drnic** [comment]
This regression in Concourse is blocking upgrade of Concourse Tutorial to v5 (since it switches to deploying BUCC in the middle to introduce credhub secrets)

**Comment by drnic** [comment]
Also ci2.starkandwayne.com runs on the bucc deployment model of concourse (if you’re interested in production envs that use bucc)

**Comment by vito** [comment]
@drnic If you've got time, a PR making the suggested changes in https://github.com/concourse/concourse-bosh-release/issues/17#issuecomment-471620183 would be the quickest route. This was never intentionally supported so I'd hesitate to call it a regression, but I'm happy to bring in explicit support for it.

**Comment by rkoster** [comment]
@vito 2 PR have been created, to address this issue:
- https://github.com/concourse/concourse/pull/3806
- https://github.com/concourse/concourse-bosh-release/pull/27

Looking forward to receiving feedback.

**Comment by vito** [comment]
all the changes for this are in now 👍
