### ISSUE TITLE
Failed to open connector cf, unknown connector type

### ISSUE THREAD

**Issue by lodener** [concourse/concourse-bosh-release#172]
# Bug Report

The recent 7.9.1 release introduced an issue with a connector for us when BOSH deploying it.

Whenever we make use of the web job's [cf_auth property](https://bosh.io/jobs/web?source=github.com/concourse/concourse-bosh-release&version=7.9.1#p%3dcf_auth), the web instance's web job will fail with the following error:
`error: server: Failed to open connector cf: failed to open connector: unknown connector type "cf"`

When reverting back to 7.9.0, all is fine. When removing the cf_auth property, the 7.9.1 deployment also succeeds without issues.

[This commit](https://github.com/concourse/concourse/commit/7c84a2deb444b0ae5568b8bb77ad7ec5b1ee7e97#diff-a34fa0a152d545781e98ee4328a9123aa0b5199cfcc571e99b293391b49efa2c) might look, to my untrained eyes, somewhat relevant?

**Comment by scott-paige** [comment]
I just encountered this issue as well when trying to upgrade our dev concourse from `7.9.0` => `7.9.1`

**Comment by xtremerui** [comment]
Fixed in 7.11
