### ISSUE TITLE
Failed to open connector cf, unknown connector type 

### ISSUE THREAD

**Issue by scott-paige** [concourse/concourse-bosh-release#176]
### Describe the bug

```
error: server: Failed to open connector cf: failed to open connector: unknown connector type "cf"
```

We encountered this error in `7.9.1` and [it was stated ](https://github.com/concourse/concourse/issues/8696#issuecomment-1461108300) that a fix for this would be pushed in `7.9.2`, however we are still seeing this error when attempting to deploy to `7.10.0`.

### Reproduction steps

1. use cf_auth 
2. deploy `7.10.0`
3. get error from `web.stderr.log`
...

### Expected behavior

That we can continue to use cloudfoundry for authentication

### Additional context

The only place that we reference `cf` is in our team configuration yamls. I went ahead and updated all of the team configs to only have the local admin user as their member, however I still encountered the error when trying to deploy. 

Is there anything else I should be changing?

**Comment by xtremerui** [comment]
This bug is fixed in 7.11
