### ISSUE TITLE
file permissions and ownership under BPM of `CONCOURSE_POSTGRES_CLIENT_KEY`

### ISSUE THREAD

**Issue by flavorjones** [concourse/concourse-bosh-release#19]
Ahoy! I'm seeing an issue with file permissions and ownership when:

* running Concourse 5.0.0
* via `concourse-bosh-deployment`
* using the ops file `concourse-bosh-deployment/cluster/operations/external-postgres-client-cert.yml`.

The TL;DR is that the file `CONCOURSE_POSTGRES_CLIENT_KEY` is created with perms `0644` and ownership by `root`, which causes problems because:

* the library `pq` requires `0600` permissions on private keys
* BPM runs the process as `vcap` meaning that if `0600` is required, then file ownership must be set to `vcap`.

There are a few ways we _could_ fix this, and so I'm seeking guidance on what y'all would like me to put into a PR.

__What I'm seeing__

Out of the box, here's what happens when `concourse-bosh-deployment` tries to use `CONCOURSE_POSTGRES_CLIENT_KEY`:

```
==> /var/vcap/sys/log/web/web.stderr.log <==
failed to migrate database: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less
```

To level-set, this is what the file permissions look like for the env files:

```
# ls -lt /var/vcap/data/jobs/web/*/config/env/*
-rw-r--r-- 1 root root 1675 Mar  9 01:51 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_TSA_HOST_KEY
-rw-r--r-- 1 root root 1188 Mar  9 01:51 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CLIENT_CERT
-rw-r--r-- 1 root root 1679 Mar  9 01:51 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
-rw-r--r-- 1 root root 1675 Mar  9 01:51 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_SESSION_SIGNING_KEY
-rw-r--r-- 1 root root  381 Mar  9 01:51 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_TSA_AUTHORIZED_KEYS_0
-rw-r--r-- 1 root root 1147 Mar  9 01:51 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CA_CERT
```

The code raising this error is [`lib/pq/ssl_permissions.go`](https://github.com/lib/pq/blob/v1.0.0/ssl_permissions.go), which is called from [`lib/pq/ssl.go`](https://github.com/lib/pq/blob/v1.0.0/ssl.go#L111-L115). There doesn't seem to be any way to omit this permissions check.

__What I've tried, Part 1__

Let's set the file permissions to `0600` as `pq` demands:

```
# chmod go-r /var/vcap/data/jobs/web/*/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
# ls -lt /var/vcap/data/jobs/web/*/config/env/*
-rw-r--r-- 1 root root 1675 Mar  9 01:57 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_TSA_HOST_KEY
-rw-r--r-- 1 root root  381 Mar  9 01:57 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_TSA_AUTHORIZED_KEYS_0
-rw-r--r-- 1 root root 1147 Mar  9 01:57 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CA_CERT
-rw-r--r-- 1 root root 1188 Mar  9 01:57 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CLIENT_CERT
-rw------- 1 root root 1679 Mar  9 01:57 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
-rw-r--r-- 1 root root 1675 Mar  9 01:57 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_SESSION_SIGNING_KEY
```

Now we get this error:

```
==> /var/vcap/sys/log/web/web.stderr.log <==
failed to migrate database: open /var/vcap/jobs/web/config/env/CONCOURSE_POSTGRES_CLIENT_KEY: permission denied
```

which of course is because BPM runs the process as `vcap` who no longer has permissions to read this file.

__What I've tried, Part 2__

So now let's also set the file ownership to `vcap`:

```
# chown vcap /var/vcap/data/jobs/web/*/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
# ls -lt /var/vcap/data/jobs/web/*/config/env/*
-rw-r--r-- 1 root root  381 Mar  9 02:47 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_TSA_AUTHORIZED_KEYS_0
-rw-r--r-- 1 root root 1675 Mar  9 02:47 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_TSA_HOST_KEY
-rw-r--r-- 1 root root 1188 Mar  9 02:47 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CLIENT_CERT
-rw------- 1 vcap root 1679 Mar  9 02:47 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
-rw-r--r-- 1 root root 1675 Mar  9 02:47 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_SESSION_SIGNING_KEY
-rw-r--r-- 1 root root 1147 Mar  9 02:47 /var/vcap/data/jobs/web/452353ea17eb7a4afbc61f44531c3c0135262640/config/env/CONCOURSE_POSTGRES_CA_CERT
```

And now the `web` job is able to connect and migrate and everything works.

__Request for Guidance__

My instinct is to fix this by ensuring that the `env_file_writer` helper in `tmpl/create_env_files.erb.tmpl` creates all files with `0600` perms and `vcap` as owner and group.

Would that approach be acceptable if I submitted a PR?

**Comment by flavorjones** [comment]
In the meantime, for anyone else who encouters this issue, the workaround I'm using is to `bosh ssh` onto the `web` VM and run this before BOSH marks the agent as failing:

```
# as root, natch
chmod go-r /var/vcap/data/jobs/web/*/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
chown vcap /var/vcap/data/jobs/web/*/config/env/CONCOURSE_POSTGRES_CLIENT_KEY
```

**Comment by vito** [comment]
Ahh thanks for the detailed report! Looks like something to account for with our env file magic.

I wonder if we should just make everything `0600`? Seems like it might be better from a security standpoint anyhow.

The fix would be in [`create_env_files.erb.tmpl`](https://github.com/concourse/concourse-bosh-release/blob/master/tmpl/create_env_files.erb.tmpl) - happy to prioritize the fix ourselves if you don't want to get involved in ERB/Go template madness. Since that template is shared by both `web` (which runs as `vcap`) and `worker` (which runs as `root`) we'd probably need to set an env or something so it knows who to `chown` it as. That could be set [here](https://github.com/concourse/concourse-bosh-release/blob/8eef6afed6b50bd661924d120d498ecb9ef294a5/jobs/web/templates/pre_start.erb.tmpl) and [here](https://github.com/concourse/concourse-bosh-release/blob/8eef6afed6b50bd661924d120d498ecb9ef294a5/jobs/worker/templates/pre_start.erb.tmpl).

**Comment by flavorjones** [comment]
I've got a branch up with commits that worked for me:

https://github.com/flavorjones/concourse-bosh-release/tree/019-flavorjones-env-file-perms

which results in:

```
# on `web` vm
$ ls -lt /var/vcap/data/jobs/web/*/config/env
total 24
-rw------- 1 vcap vcap 1675 Mar  9 17:31 CONCOURSE_TSA_HOST_KEY
-rw------- 1 vcap vcap 1675 Mar  9 17:31 CONCOURSE_SESSION_SIGNING_KEY
-rw------- 1 vcap vcap  381 Mar  9 17:31 CONCOURSE_TSA_AUTHORIZED_KEYS_0
-rw------- 1 vcap vcap 1679 Mar  9 17:31 CONCOURSE_POSTGRES_CLIENT_KEY
-rw------- 1 vcap vcap 1188 Mar  9 17:31 CONCOURSE_POSTGRES_CLIENT_CERT
-rw------- 1 vcap vcap 1147 Mar  9 17:31 CONCOURSE_POSTGRES_CA_CERT
```

Because the worker runs as `root` it appears it can still read the files despite the permissions, because everything seems to be working OK. Here's what it looks like on the worker:

```
# on `worker` vm
$ ls -lt /var/vcap/data/jobs/worker/*/config/env
total 4
-rw------- 1 vcap vcap 1675 Mar  9 17:31 CONCOURSE_TSA_WORKER_PRIVATE_KEY
```

I'm going to submit a "draft PR" out of that branch for discussion, again this scratches my itch so I'm happy to do the work.

**Comment by flavorjones** [comment]
See https://github.com/concourse/concourse-bosh-release/pull/20
