### ISSUE TITLE
documentation incorrect for build_log_retention.default_builds in v5.2.0

### ISSUE THREAD

**Issue by lrstanley** [concourse/concourse-bosh-release#37]
https://bosh.io/jobs/web?source=github.com/concourse/concourse-bosh-release&version=5.2.0#p%3dbuild_log_retention

build_log_retention.default_builds shows:

> Default days to retain build logs. 0 means unlimited.

When it should be something like:

> Default number of builds logs to retain. Will override values configured in jobs.

**Comment by vito** [comment]
It's a 'default', so it shouldn't override. What is the behavior you're observing? 🤔
